version: '3'

services:
  fortress:
    image: gazebo:latest
    container_name: fortress
    network_mode: host
    environment:
      - DISPLAY=:1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
    # entrypoint: [ "tail", "-f", "/dev/null"]
    entrypoint: [ "/bin/bash", "-c" ]
    command:
       - ign gazebo $HOME/myrobot.sdf -v4